language: node_js
node_js:
  - "7"
  - 6.9.0

sudo: required

os: osx

before_install:
  - source bash_utils/before_install.sh 

services: mongodb

notifications:
  email: false
  
before_script:
  - sleep 15
  - "until nc -z localhost 27017; do echo Waiting for MongoDB; sleep 1; done"